title: Smarthjem

# Copy resources from anywhere to www/lovelace and include them
resources:
  - url: !resource monster-card/monster-card.js
    type: js
  - url: !resource mini-media-player/mini-media-player.js?v=0.8.7
    type: module
views:
  - title: Home
    id: home
    icon: mdi:home-heart
    cards:
      - !include presence_tracker.yaml
      - !include alarm.yaml
  - !include living_room.yaml
  - !include bedrooms.yaml
  - !include outdoor.yaml
  - !include climate.yaml
  - !include system.yaml