- id: '1565609695612'
  alias: alarm_notify_away_disarmed_niklas
  trigger:
  - entity_id: group.family
    for: 00:10:00
    from: home
    platform: state
    to: not_home
  condition:
  - condition: state
    entity_id: alarm_control_panel.verisure_alarm
    state: disarmed
  action:
  - data:
      data:
        inline_keyboard:
        - Tikoble ude:/arm_away, Ignorer:/dismiss
      message: Der ser ikke ud til der er nogen personer i huset, men alermen er ikke
        tilkoblet.
      title: '*Alarm ej tikoblet*'
    service: notify.telegram_niklas
- id: '1575669623652'
  alias: all_off
  description: Slukker alt indelys, og tænder lys i indkørsel i 10 minutter hvis mørkt
  trigger:
  - entity_id: binary_sensor.all_off
    platform: state
    to: 'on'
  condition: []
  action:
  - service: automation.turn_off
    data: {}
    target:
      entity_id:
      - automation.living_room_scene_control
      - automation.living_room_kitchen_scene_control
    alias: Disable Scene Control Automations
  - service: input_select.select_option
    entity_id: input_select.living_room_mode
    data:
      option: Fra
    alias: Set Living Room Mode
  - service: homeassistant.turn_off
    data:
      entity_id:
      - input_boolean.living_room_cooking
      - light.kitchen_downlight
      - light.kitchen_table_lamps
      - light.living_room_spots
      - light.living_room_dinning_table_pendel
      - light.living_room_couch_table_pendel
      - light.living_room_lamp_at_tv
      - light.living_room_table_lamp
      - light.living_room_glass_cabinet
      - light.utility_room_table_light
      - light.corridor_spots
      - light.hallway_downlight
      - light.office_spots
      - light.william_bed_lamp
      - light.william_spots
      - light.sophia_bed_lamp
      - light.sophia_spots
    alias: Turn Off Entities
  - service: light.turn_off
    data:
      transition: 2
    target:
      area_id: 1ff4f52a04ad4c9cae3867b670a4c2a4
    alias: Turn Off Lights (Rooms)
  - service: automation.turn_on
    data: {}
    target:
      entity_id:
      - automation.living_room_scene_control
      - automation.living_room_kitchen_scene_control
    alias: Enable Scene Control Automations
  mode: single
- id: '1578147796704'
  alias: hallway_closet_on
  description: ''
  trigger:
  - entity_id: binary_sensor.hallway_closet_occupancy
    platform: state
    to: 'on'
  condition: []
  action:
  - brightness_pct: 100
    device_id: 6562e7ccde44490793da876d7ea03589
    domain: light
    entity_id: light.hallway_closet_led_panel
    type: turn_on
  mode: single
- id: '1578148039240'
  alias: hallway_closet_off
  description: ''
  trigger:
  - entity_id: binary_sensor.hallway_closet_occupancy
    for: 00:00:30
    platform: state
    to: 'off'
  condition: []
  action:
  - device_id: 6562e7ccde44490793da876d7ea03589
    domain: light
    entity_id: light.hallway_closet_led_panel
    type: turn_off
- id: '1579361543060'
  alias: sophia_sleep_mode_on
  description: ''
  trigger:
  - entity_id: binary_sensor.ihc_sophia_goodnight_start
    platform: state
    to: 'on'
  - at: '21:00:00'
    platform: time
  condition:
  - condition: state
    entity_id: switch.ihc_sophia_sleep_mode
    state: 'off'
  action:
  - entity_id: switch.ihc_sophia_sleep_mode
    service: switch.turn_on
  - brightness_pct: 25
    device_id: 95db12aab78f4f6c9055834c5f41fbca
    domain: light
    entity_id: light.sophia_bed_lamp
    type: turn_on
  - data: {}
    entity_id: light.sophia_spots
    service: light.turn_off
  mode: single
- id: '1579361605420'
  alias: sophia_sleep_mode_off
  description: ''
  trigger:
  - at: 07:00:00
    platform: time
  - entity_id: binary_sensor.ihc_sophia_goodnight_stop
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: switch.ihc_sophia_sleep_mode
    service: switch.turn_off
- id: '1581175287613'
  alias: sophia_bed_lamp_toogle
  description: ''
  trigger:
  - entity_id: binary_sensor.ihc_sophia_bed_lamp_toogle
    platform: state
    to: 'on'
  condition: []
  action:
  - service: light.toggle
    data:
      brightness_pct: 25
    target:
      device_id: 95db12aab78f4f6c9055834c5f41fbca
- id: '1581239039910'
  alias: corridor_spots_toggle
  description: ''
  trigger:
  - entity_id: binary_sensor.corridor_downlight_toogle
    platform: state
    to: 'on'
  condition: []
  action:
  - entity_id: light.corridor_spots
    service: light.toggle
    data:
      entity_id: light.corridor_spots
  mode: single
- id: '1581761391770'
  alias: corridor_spots_sleep_mode_toggle
  description: ''
  trigger:
  - platform: state
    entity_id: binary_sensor.corridor_goodnight_toogle
    to: 'on'
  condition: []
  action:
  - entity_id: input_boolean.corridor_sleep_mode
    service: input_boolean.toggle
    data:
      entity_id: input_boolean.corridor_sleep_mode
  mode: single
- id: '1584307470667'
  alias: Udendørs / Tænd spots ved døråbning
  description: Tænder udelys (spots i udhæng) når en af dørene åbnes.
  trigger:
  - entity_id: binary_sensor.driveway_doors
    platform: state
    to: 'on'
  condition:
  - condition: state
    entity_id: sensor.day_light_mode
    state: night
  - condition: state
    entity_id: light.outdoor_driveway_spots
    state: 'off'
  action:
  - service: light.turn_on
    data: {}
    target:
      entity_id: light.outdoor_driveway_spots
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.driveway_doors
      to: 'off'
      for:
        hours: 0
        minutes: 3
        seconds: 0
    timeout: 00:15:00
  - service: light.turn_off
    data: {}
    target:
      entity_id: light.outdoor_driveway_spots
  mode: single
- id: '1584869219598'
  alias: William / Climate off when window open
  description: ''
  trigger:
  - entity_id: binary_sensor.william_window
    for: 00:01
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      hvac_mode: 'off'
    entity_id: climate.william
    service: climate.set_hvac_mode
- id: '1584869307336'
  alias: William / Climate heat when window close
  description: ''
  trigger:
  - entity_id: binary_sensor.william_window
    for: 00:05
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      hvac_mode: heat
    entity_id: climate.william
    service: climate.set_hvac_mode
- id: '1584870531319'
  alias: Sophia / Climate off when window open
  description: ''
  trigger:
  - entity_id: binary_sensor.sophia_window
    for: 00:01
    platform: state
    to: 'on'
  condition: []
  action:
  - data:
      hvac_mode: 'off'
    entity_id: climate.sophia
    service: climate.set_hvac_mode
- id: '1584870587700'
  alias: Sophia / Climate heat when window close
  description: ''
  trigger:
  - entity_id: binary_sensor.sophia_window
    for: 00:05
    platform: state
    to: 'off'
  condition: []
  action:
  - data:
      hvac_mode: heat
    entity_id: climate.sophia
    service: climate.set_hvac_mode
- id: '1584981169287'
  alias: Bryggers / Vandlækage
  description: ''
  trigger:
  - type: moist
    platform: device
    device_id: 258eccf55f5c4c02bf47228e1ddb3e48
    entity_id: binary_sensor.utility_room_water_leak_water_leak
    domain: binary_sensor
  condition: []
  action:
  - repeat:
      until:
      - type: is_not_moist
        condition: device
        device_id: 258eccf55f5c4c02bf47228e1ddb3e48
        entity_id: binary_sensor.utility_room_water_leak_water_leak
        domain: binary_sensor
        for:
          hours: 0
          minutes: 5
          seconds: 0
      sequence:
      - service: notify.mobile_app_niklas_mobile
        data:
          message: Der er detekteret vandlækage i bryggers!
          title: 'Vandlækage '
      - service: notify.telegram_niklas
        data:
          message: Der er detekteret vandlækage i bryggers!
          title: Vandlækage
      - delay:
          hours: 0
          minutes: 1
          seconds: 0
          milliseconds: 0
      - device_id: 716570a6eb884b418cd7ce060c44e982
        domain: light
        entity_id: light.utility_room_table_light
        type: flash
- id: '1586774175973'
  alias: Bryggers / Lys under skabe / Lysstyring (Tænd)
  description: ''
  trigger:
  - entity_id: binary_sensor.utility_room_table_light_on
    platform: state
    to: 'on'
  condition: []
  action:
  - device_id: 716570a6eb884b418cd7ce060c44e982
    domain: light
    entity_id: light.utility_room_table_light
    type: turn_on
- id: '1586774239550'
  alias: Bryggers / Lys under skabe / Lysstyring (Sluk)
  description: ''
  trigger:
  - entity_id: binary_sensor.utility_room_table_light_off
    platform: state
    to: 'on'
  - device_id: 0923b24cc0d844b3a95017cfa56710f0
    domain: binary_sensor
    entity_id: binary_sensor.utility_room_occupancy
    for:
      hours: 0
      minutes: 15
      seconds: 0
    platform: device
    type: no_motion
  condition: []
  action:
  - device_id: 716570a6eb884b418cd7ce060c44e982
    domain: light
    entity_id: light.utility_room_table_light
    type: turn_off
- id: '1598003536624'
  alias: alarm_warn_fridge_door_open
  description: Giver en advarsel hvis fryseren står åbent
  trigger: []
  condition: []
  action:
  - data:
      text: Fryseren står åbent
    service: script.warning_say
  - data:
      message: 'ADVARSEL: Fryseren står åbent!'
    service: notify.mobile_app_niklas_samsung_s8
  mode: single
- id: '1601019068519'
  alias: Bryggers / Lys under skabe / Lysstyring (Kip)
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 7ba866fec10d46a0b9224b0efb01e06c
    type: click
    subtype: single
    discovery_id: 0x00158d000424cd00 click_single
  condition: []
  action:
  - type: toggle
    device_id: 716570a6eb884b418cd7ce060c44e982
    entity_id: light.utility_room_table_light
    domain: light
  mode: single
- id: '1615152521529'
  alias: Køkken / Madlavning - Aktiver ved aktivitet
  description: Aktiverer madlavnings scene ved aktivitet i køkkrenet (køkkenbord)
  trigger:
  - type: motion
    platform: device
    device_id: 5f3cbabebae0a6f61b35659a8a11c3d5
    entity_id: binary_sensor.kitchen_table_occupancy_occupancy
    domain: binary_sensor
  condition:
  - condition: state
    entity_id: input_boolean.living_room_cooking
    state: 'off'
  - condition: or
    conditions:
    - condition: time
      after: 06:00
      before: 09:00
    - condition: time
      after: '16:30'
      before: '19:00'
  action:
  - service: input_boolean.turn_on
    target:
      entity_id: input_boolean.living_room_cooking
  mode: single
- id: '1615498005717'
  alias: LK Fuga Test
  description: ''
  trigger:
  - platform: device
    domain: mqtt
    device_id: 1223f1ef6ef4aaf6d0ee90904e83bc78
    type: action
    subtype: on_s1
    discovery_id: 0x60a423fffe50109c action_on_s1
  condition: []
  action:
  - type: toggle
    device_id: 1223f1ef6ef4aaf6d0ee90904e83bc78
    entity_id: switch.0x60a423fffe50109c_l1
    domain: switch
  mode: single
- id: '1615725877774'
  alias: William / TagReader
  description: ''
  trigger:
    platform: tag
    tag_id:
    - B0-00-0C-32
    - 55-9B-15-2A
    - 04-0C-92-42-21-6F-81
    - C2-0F-B9-3D
  condition:
  - '{{ trigger.event.data.tag_id in tags }}'
  action:
  - variables:
      media_content_id: '{{ tags[trigger.event.data.tag_id].media_content_id }}'
      media_content_type: '{{ tags[trigger.event.data.tag_id].media_content_type }}'
  - service: media_player.play_media
    data:
      media_content_id: '{{ media_content_id }}'
      media_content_type: '{{ media_content_type }}'
    target:
      entity_id: media_player.william_nest_mini
  mode: single
  variables:
    tags:
      B0-00-0C-32:
        media_content_id: 'plex://{"playlist_name": "Børnemusik - Bamse & Kylling",
          "shuffle": "1"}'
        media_content_type: playlist
      55-9B-15-2A:
        media_content_id: 'plex://{"playlist_name": "Børnemusik - Kaj & Andrea", "shuffle":
          "1"}'
        media_content_type: playlist
      04-0C-92-42-21-6F-81:
        media_content_id: 'plex://{"playlist_name": "Børnemusik - Kaj & Andrea", "shuffle":
          "1"}'
        media_content_type: playlist
      C2-0F-B9-3D:
        media_content_id: 'plex://{"playlist_name": "Børnemusik - Rock", "shuffle":
          "1"}'
        media_content_type: playlist
- id: '1627762008497'
  alias: test
  description: ''
  trigger: []
  condition: []
  action:
  - service: script.on_off_dim
    data:
      button: input_boolean.bedroom_spots_button
  mode: single
- id: '1628882812283'
  alias: bedroom_wake_up
  description: ''
  trigger:
  - platform: time
    at: 05:45:00
  condition:
  - condition: state
    entity_id: binary_sensor.workday_sensor
    state: 'on'
  action:
  - service: script.bedroom_simulated_runrise
    data:
      delay: 300
  mode: single
