homeassistant:
  # Customization file
  customize: !include customize.yaml
  packages:  !include_dir_named packages

default_config:

http:
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem

# Discover some devices automatically
discovery:
  ignore:
    - philips_hue
    - google_cast

# Tracked history is kept for 10 days
recorder: !include recorder.yaml

# Enables support for tracking state changes over time
history:
  include:
    entities:
      # Device Trackers
      - device_tracker.niklas
      - device_tracker.karina
      
# View all events in a logbook
logbook:
  exclude:
    domains:
      - group
    entities:
      # Exclude motion detectors, since they will 
      # switch on/off a lot.
      - binary_sensor.utility_room_occupancy 
      - binary_sensor.corridor_occupancy
      - binary_sensor.hallway_occupancy
      - binary_sensor.hallway_closet_occupancy

# Text to speech
tts:
  - platform: google_translate
    service_name: google_say

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
