light:
  - platform: group
    name: corridor_spots
    entities:
      - light.corridor_spot_1
      - light.corridor_spot_2
      - light.corridor_spot_3

input_boolean:
  corridor_sleep_mode:
    name: Godnat gang
    icon: mdi:sleep
  corridor_night_light:
    name: Gang / Konstant nattelys
    icon: mdi:weather-night

# Automations
automation:
  - alias: corridor_spots_sleep_mode_on
    description: Gang / Tænder natlys ved aktivering af nat, nattelys eller bevægelse
    id: 4a7c290a-7322-4c3f-acdb-61a5d119d684
    trigger:
      - platform: state
        entity_id: input_boolean.corridor_sleep_mode
        to: 'on'
      - platform: state
        entity_id: input_boolean.corridor_night_light
        to: 'on'
      - platform: state
        entity_id: binary_sensor.corridor_occupancy
        to: 'on'
    condition:
      - condition: state
        entity_id: input_boolean.corridor_sleep_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.deactivate_sleep_mode_on_motion
        state: 'off'
    action:
      - service: light.turn_off
        data:
          entity_id: light.corridor_spots
      - service: light.turn_on
        data:
          entity_id: light.corridor_spot_2
          kelvin: 6500
          brightness_pct: 1
  - alias: corridor_spots_sleep_mode_on_auto_off
    description: Gang / Slukker natlys efter endt bevægelse (anvendes ikke hvis nattelys er tændt)
    id: 93b039e3-09f5-4d04-ba16-2a37e2149060
    trigger:
      - platform: state
        entity_id: input_boolean.corridor_sleep_mode
        to: 'on'
        for: '00:03:00'
      - platform: state
        entity_id: binary_sensor.corridor_occupancy
        to: 'off'
        for: '00:03:00'
    condition:
      - condition: state
        entity_id: input_boolean.corridor_sleep_mode
        state: 'on'
      - condition: state
        entity_id: input_boolean.corridor_night_light
        state: 'off'
      - condition: state
        entity_id: input_boolean.deactivate_sleep_mode_on_motion
        state: 'off'
    action:
      - service: light.turn_off
        data:
          entity_id: light.corridor_spots
  - alias: corridor_spots_auto_on
    description: Gang / Tænder lys ved skumring
    id: 26869a0e-94ae-4e95-b82d-294de1ac80c4
    trigger:
      - platform: state
        entity_id: sensor.day_night
        to: 'night'
      - platform: state
        entity_id: input_boolean.corridor_sleep_mode
        to: 'off'
    condition:
      - condition: state
        entity_id: sensor.day_night
        state: 'night'
      - condition: state
        entity_id: input_boolean.corridor_sleep_mode
        state: 'off'
    action:
      - service: light.turn_on
        data:
          entity_id: light.corridor_spots
          kelvin: 2800
          brightness_pct: 50
  - alias: corridor_spots_auto_off
    description: Gang / Slukker lys ved skumring frafald
    id: 7e1e77f8-4e62-4cd5-be86-9a973e82c32a
    trigger:
      - platform: state
        entity_id: sensor.day_night
        to: 'day'
    action:
      - service: light.turn_off
        data:
          entity_id: light.corridor_spots
      - service: input_boolean.turn_off
        data:
          entity_id: input_boolean.corridor_sleep_mode
