- id: all_off_east
  alias: Sluk Øst
  trigger:
  - platform: state
    entity_id: binary_sensor.all_off_east
    to: 'on'
  condition: []
  action:
  - service: light.turn_off
    entity_id:
      - light.living_room_dinning_table_pendel
      - light.living_room_couch_table_pendel
      - light.living_room_lamp_at_tv
      - light.living_room_lamp1      
      - light.living_room_glass_cabinet

- id: living_room_scene_spise
  alias: living_room_scene_spise
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_scene_spise
  action:
  - service: scene.turn_on
    entity_id: scene.spise

- id: living_room_scene_hygge
  alias: living_room_scene_hygge
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_scene_hygge
  action:
  - service: scene.turn_on
    entity_id: scene.hygge

- id: living_room_scene_cleaning
  alias: 'IHC Input / Scene: Rengøring'
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_scene_cleaning
  action:
  - service: scene.turn_on
    entity_id: scene.rengring

- alias: living_room_dinning_table_pendel_up
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_dinning_table_pendel_up
  action:
  - service: light.turn_on
    entity_id: light.living_room_dinning_table_pendel
    data_template:
      brightness: '{{states.light.living_room_dinning_table_pendel.attributes.brightness|int + 25}}'

- alias: living_room_dinning_table_pendel_down
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_dinning_table_pendel_down
  action:
  - service: light.turn_on
    entity_id: light.living_room_dinning_table_pendel
    data_template:
      brightness: '{{states.light.living_room_dinning_table_pendel.attributes.brightness|int - 25}}'

- alias: living_room_dinning_table_pendel_toggle
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_dinning_table_pendel_toggle
  action:
  - service: light.toggle
    entity_id: light.living_room_dinning_table_pendel

# Living Room / Lamp at TV
# alias: living_room_lamp_at_tv_up
# hide_entity: True
# trigger:
# - platform: state
#   entity_id: binary_sensor.living_room_lamp_at_tv_up
# action:
# - service: light.turn_on
#   entity_id: light.living_room_lamp_at_tv
#   data_template:
#     brightness: '{{states.light.living_room_lamp_at_tv.attributes.brightness|int + 25}}'
#
# alias: living_room_lamp_at_tv_down
# hide_entity: True
# trigger:
# - platform: state
#   entity_id: binary_sensor.living_room_lamp_at_tv_down
# action:
# - service: light.turn_on
#   entity_id: light.living_room_lamp_at_tv
#   data_template:
#     brightness: '{{states.light.living_room_lamp_at_tv.attributes.brightness|int - 25}}'

- alias: living_room_lamp_at_tv_toggle
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_lamp_at_tv_toggle
  action:
  - service: light.toggle
    entity_id: light.living_room_lamp1

- alias: living_room_couch_table_pendel_toggle
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_couch_table_pendel_toggle
  action:
  - service: light.toggle
    entity_id: light.living_room_couch_table_pendel

- alias: welcome_home_at_night
  trigger:
  - platform: state
    entity_id: device_tracker.niklas
    from: 'not_home'
    to: 'home'
  - platform: state
    entity_id: device_tracker.karina
    from: 'not_home'
    to: 'home'
  condition:
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: light.outdoor_driveway_spots
    state: 'off'
  - condition: state
    entity_id: light.living_room_spots
    state: 'off'
  action:
  - service: light.turn_on
    entity_id: light.outdoor_driveway_spots
  - service: light.turn_on
    entity_id: light.living_room_spots
    data_template:
      brightness: 64
