homeassistant:
  customize:
    climate.living_room:
      friendly_name: Stue
    climate.william:
      friendly_name: William
    climate.hall:
      friendly_name: Gang

    sensor.living_room_temp:
      friendly_name: Stue / Temp.
    sensor.william_temp:
      friendly_name: William / Temp.
    sensor.hall_temp:
      friendly_name: Gang / Temp.

    automation.climate_night_mode_start:
      friendly_name: Natsænkning Start
    automation.climate_night_mode_end:
      friendly_name: Natsænkning Slut

climate:
  - platform: mqtt
    name: living_room
    modes:
      - 'off'
      - 'heat'
    current_temperature_topic: 'heat/floor84F3EB9FC608/0/current'
    temperature_command_topic: 'heat/floor84F3EB9FC608/0/target_set'
    temperature_state_topic: 'heat/floor84F3EB9FC608/0/target'
    availability_topic: 'heat/floor84F3EB9FC608/online'
    payload_available: 'True'
    payload_not_available: 'False'
    mode_state_topic: 'heat/floor84F3EB9FC608/0/output'
    mode_state_template: >-
      {{ 'heat' if value == 'on' else 'off' }}
    qos: 0
  - platform: mqtt
    name: william
    modes:
      - 'off'
      - 'heat'
    current_temperature_topic: 'heat/floor84F3EB9FC608/3/current'
    temperature_command_topic: 'heat/floor84F3EB9FC608/3/target_set'
    temperature_state_topic: 'heat/floor84F3EB9FC608/3/target'
    availability_topic: 'heat/floor84F3EB9FC608/online'
    payload_available: 'True'
    payload_not_available: 'False'
    mode_state_topic: 'heat/floor84F3EB9FC608/3/output'
    mode_state_template: >-
      {{ 'heat' if value == 'on' else 'off' }}
    qos: 0
  - platform: mqtt
    name: sophia
    modes:
      - 'off'
      - 'heat'
    current_temperature_topic: 'heat/floor84F3EB9FC608/4/current'
    temperature_command_topic: 'heat/floor84F3EB9FC608/4/target_set'
    temperature_state_topic: 'heat/floor84F3EB9FC608/4/target'
    availability_topic: 'heat/floor84F3EB9FC608/online'
    payload_available: 'True'
    payload_not_available: 'False'
    mode_state_topic: 'heat/floor84F3EB9FC608/4/output'
    mode_state_template: >-
      {{ 'heat' if value == 'on' else 'off' }}
    qos: 0
  - platform: mqtt
    name: hall
    modes:
      - 'off'
      - 'heat'
    current_temperature_topic: 'heat/floor84F3EB9FC608/6/current'
    temperature_command_topic: 'heat/floor84F3EB9FC608/6/target_set'
    temperature_state_topic: 'heat/floor84F3EB9FC608/6/target'
    availability_topic: 'heat/floor84F3EB9FC608/online'
    payload_available: 'True'
    payload_not_available: 'False'
    mode_state_topic: 'heat/floor84F3EB9FC608/6/output'
    mode_state_template: >-
      {{ 'heat' if value == 'on' else 'off' }}
    qos: 0

sensor:
  - platform: mqtt
    name: living_room_temp
    state_topic: 'heat/floor84F3EB9FC608/0/current'
    unit_of_measurement: '°C'
    availability_topic: 'heat/floor84F3EB9FC608/online'
    payload_available: 'True'
    payload_not_available: 'False'
  - platform: mqtt
    name: william_temp
    state_topic: 'heat/floor84F3EB9FC608/3/current'
    unit_of_measurement: '°C'
    availability_topic: 'heat/floor84F3EB9FC608/online'
    payload_available: 'True'
    payload_not_available: 'False'
  - platform: mqtt
    name: sophia_temp
    state_topic: 'heat/floor84F3EB9FC608/4/current'
    unit_of_measurement: '°C'
    availability_topic: 'heat/floor84F3EB9FC608/online'
    payload_available: 'True'
    payload_not_available: 'False'
  - platform: mqtt
    name: hall_temp
    state_topic: 'heat/floor84F3EB9FC608/6/current'
    unit_of_measurement: '°C'
    availability_topic: 'heat/floor84F3EB9FC608/online'
    payload_available: 'True'
    payload_not_available: 'False'

input_number:
  climate_target_temperature_living_room_day:
    name: 'Stue / Dag Temp.'
    icon: mdi:thermometer 
    initial: 22
    min: 16
    max: 28
    step: 1
    mode: box
  climate_target_temperature_living_room_night:
    name: 'Stue / Nat Temp.'
    icon: mdi:thermometer
    initial: 18
    min: 16
    max: 28
    step: 1
    mode: box
  climate_target_temperature_bed_rooms_day:
    name: 'Værelser / Dag Temp.'
    icon: mdi:thermometer
    initial: 20
    min: 16
    max: 28
    step: 1
    mode: box
  climate_target_temperature_bed_rooms_night:
    name: 'Værelser / Nat Temp.'
    icon: mdi:thermometer
    initial: 18
    min: 16
    max: 28
    step: 1
    mode: box

input_boolean:
  climate_night_mode:
    name: 'Natsænkning'

input_datetime:
  climate_night_mode_start:
    name: 'Natsænkning Start'
    has_date: false
    has_time: true
  climate_night_mode_end:
    name: 'Natsænkning Slut'
    has_date: false
    has_time: true

#automation:
#- alias: climate_night_mode_start
#  trigger:
#    - platform: template
#      value_template: '{{ (states.input_datetime.climate_night_mode_start.attributes.timestamp | int | timestamp_custom("%H:%M", False)) == states.sensor.time.state }}'
#  condition:
#    condition: state
#    entity_id: input_boolean.climate_night_mode
#    state: 'on'
#  action:
#    - service: climate.set_temperature
#      data_template:
#        entity_id: climate.living_room
#        temperature: '{{ states.input_number.climate_target_temperature_living_room_night.state }}'
#    - service: climate.set_temperature
#      data_template:
#        entity_id: climate.william
#        temperature: '{{ states.input_number.climate_target_temperature_bed_rooms_night.state }}'
#    - service: climate.set_temperature
#      data_template:
#        entity_id: climate.hall
#        temperature: '{{ states.input_number.climate_target_temperature_bed_rooms_night.state }}'
#- alias: climate_night_mode_end
#  trigger:
#    - platform: template
#      value_template: '{{ (states.input_datetime.climate_night_mode_end.attributes.timestamp | int | timestamp_custom("%H:%M", False)) == states.sensor.time.state }}'
#  condition:
#    condition: state
#    entity_id: input_boolean.climate_night_mode
#    state: 'on'
#  action:
#    - service: climate.set_temperature
#      data_template:
#        entity_id: climate.living_room
#        temperature: '{{ states.input_number.climate_target_temperature_living_room_day.state }}'
#    - service: climate.set_temperature
#      data_template:
#        entity_id: climate.william
#        temperature: '{{ states.input_number.climate_target_temperature_bed_rooms_day.state }}'
#    - service: climate.set_temperature
#      data_template:
#        entity_id: climate.hall
#        temperature: '{{ states.input_number.climate_target_temperature_bed_rooms_day.state }}'
