homeassistant:
  customize:
    climate.living_room:
      friendly_name: Stue
    climate.william:
      friendly_name: William
    climate.hall:
      friendly_name: Gang

    sensor.living_room_temp:
      friendly_name: Stue / Temp.
    sensor.william_temp:
      friendly_name: William / Temp.
    sensor.hall_temp:
      friendly_name: Gang / Temp.

climate:
  - platform: mqtt
    name: living_room
    modes:
      - 'off'
      - 'heat'
    current_temperature_topic: 'heat/floorB4E62D44BFFA/0/current'
    temperature_command_topic: 'heat/floorB4E62D44BFFA/0/target_set'
    temperature_state_topic: 'heat/floorB4E62D44BFFA/0/target'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
    mode_state_topic: 'heat/floorB4E62D44BFFA/0/output'
    mode_state_template: >-
      {{ 'heat' if value == 'on' else 'off' }}
    qos: 0
  - platform: mqtt
    name: william
    modes:
      - 'off'
      - 'heat'
    current_temperature_topic: 'heat/floorB4E62D44BFFA/3/current'
    temperature_command_topic: 'heat/floorB4E62D44BFFA/3/target_set'
    temperature_state_topic: 'heat/floorB4E62D44BFFA/3/target'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
    mode_state_topic: 'heat/floorB4E62D44BFFA/3/output'
    mode_state_template: >-
      {{ 'heat' if value == 'on' else 'off' }}
    qos: 0
  - platform: mqtt
    name: hall
    modes:
      - 'off'
      - 'heat'
    current_temperature_topic: 'heat/floorB4E62D44BFFA/6/current'
    temperature_command_topic: 'heat/floorB4E62D44BFFA/6/target_set'
    temperature_state_topic: 'heat/floorB4E62D44BFFA/6/target'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
    mode_state_topic: 'heat/floorB4E62D44BFFA/6/output'
    mode_state_template: >-
      {{ 'heat' if value == 'on' else 'off' }}
    qos: 0

sensor:
  - platform: mqtt
    name: living_room_temp
    state_topic: 'heat/floorB4E62D44BFFA/0/current'
    unit_of_measurement: '°C'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
  - platform: mqtt
    name: hall_temp
    state_topic: 'heat/floorB4E62D44BFFA/3/current'
    unit_of_measurement: '°C'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
  - platform: mqtt
    name: william_temp
    state_topic: 'heat/floorB4E62D44BFFA/6/current'
    unit_of_measurement: '°C'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
