homeassistant:
  customize:
    climate.living_room:
      friendly_name: Stue
    climate.william:
      friendly_name: William
    climate.hall:
      friendly_name: Gang

    sensor.living_room_temp:
      friendly_name: Stue / Temp.
    sensor.william_temp:
      friendly_name: William / Temp.
    sensor.hall_temp:
      friendly_name: Gang / Temp.

climate:
  - platform: mqtt
    name: living_room
    modes:
      - 'off'
      - 'heat'
    current_temperature_topic: 'heat/floorB4E62D44BFFA/0/current'
    temperature_command_topic: 'heat/floorB4E62D44BFFA/0/target_set'
    temperature_state_topic: 'heat/floorB4E62D44BFFA/0/target'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
    mode_state_topic: 'heat/floorB4E62D44BFFA/0/output'
    mode_state_template: >-
      {{ 'heat' if value == 'on' else 'off' }}
    qos: 0
  - platform: mqtt
    name: william
    modes:
      - 'off'
      - 'heat'
    current_temperature_topic: 'heat/floorB4E62D44BFFA/3/current'
    temperature_command_topic: 'heat/floorB4E62D44BFFA/3/target_set'
    temperature_state_topic: 'heat/floorB4E62D44BFFA/3/target'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
    mode_state_topic: 'heat/floorB4E62D44BFFA/3/output'
    mode_state_template: >-
      {{ 'heat' if value == 'on' else 'off' }}
    qos: 0
  - platform: mqtt
    name: hall
    modes:
      - 'off'
      - 'heat'
    current_temperature_topic: 'heat/floorB4E62D44BFFA/6/current'
    temperature_command_topic: 'heat/floorB4E62D44BFFA/6/target_set'
    temperature_state_topic: 'heat/floorB4E62D44BFFA/6/target'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
    mode_state_topic: 'heat/floorB4E62D44BFFA/6/output'
    mode_state_template: >-
      {{ 'heat' if value == 'on' else 'off' }}
    qos: 0

sensor:
  - platform: mqtt
    name: living_room_temp
    state_topic: 'heat/floorB4E62D44BFFA/0/current'
    unit_of_measurement: '°C'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
  - platform: mqtt
    name: hall_temp
    state_topic: 'heat/floorB4E62D44BFFA/3/current'
    unit_of_measurement: '°C'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'
  - platform: mqtt
    name: william_temp
    state_topic: 'heat/floorB4E62D44BFFA/6/current'
    unit_of_measurement: '°C'
    availability_topic: 'heat/floorB4E62D44BFFA/online'
    payload_available: 'True'
    payload_not_available: 'False'

input_number:
  climate_target_temperature_living_room_day:
    name: 'Stue / Dag Temp.'
    icon: mdi:thermometer 
    initial: 22
    min: 16
    max: 28
    step: 1
    mode: box
  climate_target_temperature_living_room_night:
    name: 'Stue / Nat Temp.'
    icon: mdi:thermometer
    initial: 18
    min: 16
    max: 28
    step: 1
    mode: box
  climate_target_temperature_bed_rooms_day:
    name: 'Værelser / Dag Temp.'
    icon: mdi:thermometer
    initial: 20
    min: 16
    max: 28
    step: 1
    mode: box
  climate_target_temperature_bed_rooms_night:
    name: 'Værelser / Nat Temp.'
    icon: mdi:thermometer
    initial: 18
    min: 16
    max: 28
    step: 1
    mode: box

input_boolean:
  climate_night_mode:
    name: 'Natsænkning'

input_datetime:
  climate_night_mode_start:
    name: 'Natsænkning Start'
    has_date: false
    has_time: true
  climate_night_mode_end:
    name: 'Natsænkning Slut'
    has_date: false
    has_time: true
