connectedcars:
  username: !secret connectedcars_username
  password: !secret connectedcars_password
  namespace: 'semler:minvolkswagen'

sensor:
  - platform: template
    sensors:
      volkswagen_golf_target_odometer:
        friendly_name: "Volkswagen Golf Target Odometer"
        unit_of_measurement: 'km'        
        entity_id: sensor.date
        value_template: "{{ ((now().date() - strptime('2019-03-28', '%Y-%m-%d').date()).days * 15000/365) | round(0) }}"

utility_meter:
  volkswagen_golf_odometer_monthly:
    source: sensor.volkswagen_golf_odometer
    cycle: monthly
  volkswagen_golf_odometer_weeky:
    source: sensor.volkswagen_golf_odometer
    cycle: weekly

automation:
- alias: notify_car_near_home
  trigger:
  - entity_id: device_tracker.connectedcars_140642
    event: enter
    platform: zone
    zone: zone.near_home
  action:
  - service: notify.telegram_niklas
    data:
      message: "*Bil er næsten hjemme*"
  - service: notify.telegram_niklas
    data_template:
      message: Bil
      data:
        location:
          latitude: "{{state_attr('device_tracker.connectedcars_140642', 'latitude')}}"
          longitude: "{{state_attr('device_tracker.connectedcars_140642', 'longitude')}}"
