group:
  christmas_lights:
    name: 'Julelys'
    entities:
      #- switch.outdoor_garden
      - switch.outdoor_christmas_light_driveway
      - light.living_room_christmas_star

input_boolean:
  christmas_light:
    name: 'Julelys'
    icon: 'mdi:pine-tree'

input_datetime:
  christmas_light_start:
    name: 'Julelys Start'
    has_date: false
    has_time: true
  christmas_light_end:
    name: 'Julelys Slut'
    has_date: false
    has_time: true

automation:
- alias: outdoor_christmas_lights_on
  trigger:
  - platform: sun
    event: sunset
    offset: "00:00:00"
  - platform: time
    at: input_datetime.christmas_light_start
  condition:
    condition: state
    entity_id: input_boolean.christmas_light
    state: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: group.christmas_lights
- alias: outdoor_christmas_lights_off
  trigger:
  - platform: time
    at: input_datetime.christmas_light_end
  - platform: sun
    event: sunrise
    offset: "00:00:00"
  condition:
    condition: state
    entity_id: input_boolean.christmas_light
    state: 'on'
  action:
    service: homeassistant.turn_off
    entity_id: group.christmas_lights
