sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
  - platform: template
    sensors:
      period_of_day:
        friendly_name: 'Dag/nat (med skumring/daggry)'
        value_template: >-
          {% if states.sun.sun.attributes.rising and -6 <= states.sun.sun.attributes.elevation and states.sun.sun.attributes.elevation < 3 %}
            dusk
          {% elif not states.sun.sun.attributes.rising and -6 <= states.sun.sun.attributes.elevation and states.sun.sun.attributes.elevation < 3 %}
            dawn
          {% elif states.sun.sun.attributes.elevation < -6 %}
            night
          {% else %}
            day
          {% endif %}
        icon_template: >-
          {% if states.sun.sun.attributes.rising and -6 <= states.sun.sun.attributes.elevation and states.sun.sun.attributes.elevation < 3 %}
            mdi:weather-sunset-down
          {% elif not states.sun.sun.attributes.rising and -6 <= states.sun.sun.attributes.elevation and states.sun.sun.attributes.elevation < 3 %}
            mdi:weather-sunset-up
          {% elif states.sun.sun.attributes.elevation < -6 %}
            mdi:weather-night
          {% else %}
            mdi:weather-sunny
          {% endif %}
      day_night:
        friendly_name: 'Dag/nat'
        value_template: >-
          {% if states.sun.sun.attributes.rising and states.sun.sun.attributes.elevation < 3 %}
            night
          {% elif not states.sun.sun.attributes.rising and states.sun.sun.attributes.elevation < 3 %}
            night
          {% else %}
            day
          {% endif %}
        icon_template: >-
          {% if states.sun.sun.attributes.rising and states.sun.sun.attributes.elevation < 3 %}
            mdi:weather-night
          {% elif not states.sun.sun.attributes.rising and states.sun.sun.attributes.elevation < 3 %}
            mdi:weather-night
          {% else %}
            mdi:weather-sunny
          {% endif %}
