homeassistant:
  customize:
    sensor.washer_status:
      friendly_name: Vaskemaskine
      icon: mdi:washing-machine
    sensor.dryer_status:
      friendly_name: Tørretumbler
      icon: mdi:tumble-dryer

#homeconnect:
#  client_id: "87E6954A7EF972807E11C56A3BEFA1B9FBAC0EEA33645FA01CFF906DE73182C6"
#  client_secret: "76AD2C00E919C741788FF47249E6995D89938C6AAB6A613FB95133BC5C3C7B15"

sensor:
  - platform: mqtt
    name: washer_status
    state_topic: "home_connect/washer/status"
  - platform: mqtt
    name: dryer_status
    state_topic: "home_connect/dryer/status"

automation:
  - alias: ifttt_home_connect
    trigger:
      platform: event
      event_type: ifttt_webhook_received
      event_data:
        source: home_connect
    action:
      - service: mqtt.publish
        data_template:
          topic: 'home_connect/{{trigger.event.data.device}}/status'
          payload: '{{trigger.event.data.status}}'
          retain: true

