automation:
  - alias: ifttt_webhook_received
    trigger:
      platform: event
      event_type: ifttt_webhook_received
    action:
      - service: logbook.log
        data_template:
          name: "IFTTT Webhook Received: "
          message: >
            {{trigger.event.data}}
