ihc:
  - url: !secret ihc_url
    username: !secret ihc_username
    password: !secret ihc_password
    auto_setup: false
    info: true
    light:
      # Stue
      - id: 787549
        name: living_room_spots
        dimmable: True
      - id: 2440539
        name: living_room_glass_cabinet
      # Køkken
      - id: 2087518
        name: kitchen_table_lamps
        on_id: 2089233
        off_id: 2089489
      #- id: 2802270
      #  name: kitchen_table_lamps #ledigt relæ
      #  on_id: 2089233
      #  off_id: 2089489
      - id: 2842973
        name: kitchen_downlight
        dimmable: True
      # Bryggers
      - id: 2450779
        name: utility_room_downlight
      - id: 2452315
        name: utility_room_table_downlight
      # Udendørs
      - id: 1911899
        name: outdoor_garden_lamps
      - id: 2174555
        name: outdoor_driveway_spots
      - id: 2404443
        name: outdoor_carport_lamps
      # Børneværelse 1
      - id: 2207325
        name: william_spots
        dimmable: True
    switch:
      - id: 2403675
        name: outdoor_garden
    binary_sensor:
      - id: 2715154
        name: corridor_pir
        type: motion
      - id: 2512402
        name: all_off
      - id: 1960722
        name: all_off_east
      - id: 2436882
        name: living_room_scene_cleaning
      - id: 2350354
        name: living_room_scene_spise
      - id: 2348050
        name: living_room_scene_hygge
      - id: 2832914
        name: living_room_scene_cooking
      - id: 2144274
        name: living_room_dinning_table_pendel_up
      - id: 2144530
        name: living_room_dinning_table_pendel_down
      - id: 2145810
        name: living_room_dinning_table_pendel_toggle
      - id: 2358546
        name: living_room_couch_table_pendel_up
      - id: 2358802
        name: living_room_couch_table_pendel_down
      - id: 2359058
        name: living_room_couch_table_pendel_toggle
      - id: 2150674
        name: living_room_lamp_at_tv_up
      - id: 2150930
        name: living_room_lamp_at_tv_down
      - id: 2151186
        name: living_room_lamp_at_tv_toggle
      - id: 2210652
        name: william_bed_lamp_toogle
      - id: 2210908
        name: william_goodnight_toogle

# Automations
automation:
- alias: living_room_dinning_table_pendel_up
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_dinning_table_pendel_up
  action:
  - service: light.turn_on
    entity_id: light.living_room_dinning_table_pendel
    data_template:
      brightness: '{{states.light.living_room_dinning_table_pendel.attributes.brightness|int + 25}}'

- alias: living_room_dinning_table_pendel_down
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_dinning_table_pendel_down
  action:
  - service: light.turn_on
    entity_id: light.living_room_dinning_table_pendel
    data_template:
      brightness: '{{states.light.living_room_dinning_table_pendel.attributes.brightness|int - 25}}'

- alias: living_room_dinning_table_pendel_toggle
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_dinning_table_pendel_toggle
  action:
  - service: light.toggle
    entity_id: light.living_room_dinning_table_pendel

# Living Room / Lamp at TV
# alias: living_room_lamp_at_tv_up
# hide_entity: True
# trigger:
# - platform: state
#   entity_id: binary_sensor.living_room_lamp_at_tv_up
# action:
# - service: light.turn_on
#   entity_id: light.living_room_lamp_at_tv
#   data_template:
#     brightness: '{{states.light.living_room_lamp_at_tv.attributes.brightness|int + 25}}'
#
# alias: living_room_lamp_at_tv_down
# hide_entity: True
# trigger:
# - platform: state
#   entity_id: binary_sensor.living_room_lamp_at_tv_down
# action:
# - service: light.turn_on
#   entity_id: light.living_room_lamp_at_tv
#   data_template:
#     brightness: '{{states.light.living_room_lamp_at_tv.attributes.brightness|int - 25}}'

- alias: living_room_lamp_at_tv_toggle
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_lamp_at_tv_toggle
  action:
  - service: light.toggle
    entity_id: light.living_room_lamp1

- alias: living_room_couch_table_pendel_toggle
  hide_entity: True
  trigger:
  - platform: state
    entity_id: binary_sensor.living_room_couch_table_pendel_toggle
  action:
  - service: light.toggle
    entity_id: light.living_room_couch_table_pendel
