input_select:
  living_room_mode:
    name: Stue / Program
    options:
      - Spise
      - Hygge
      - Fra
    icon: mdi:robot

media_player:
  #- platform: androidtv
  #  host: 10.0.1.10
  #  name: living_room_androidtv
  #  adb_server_ip: 127.0.0.1
  #  adb_server_port: 5037
  - platform: kodi
    name: living_room_kodi
    host: 10.0.1.11
    port: 80
    enable_websocket: false

sensor:
  - platform: mqtt
    name: living_room_scene
    state_topic: "living_room/scene"
    value_template: >
      {% if is_state(value, 'scening') -%}
        {{ states[value.split('.')[0]][value.split('.')[1]].attributes.friendly_name }}
      {%- else -%}
        Ingen
      {%- endif %}

# Automations
automation:
  # This automation listen for changes in living_room_mode and period_of_day and publishes a matching scene to mqtt.
  - alias: living_room_scene_control
    trigger:
      - platform: state
        entity_id: sensor.period_of_day
      - platform: state
        entity_id: input_select.living_room_mode
    action:
      - service: mqtt.publish
        data_template:
          topic: living_room/scene
          retain: true
          payload: >
            {% set default_scene = 'scene.living_room_' + states('input_select.living_room_mode').lower() %}
            {% set period_of_day_scene = default_scene + '_' + states('sensor.period_of_day').lower() %}
            {% set day_night_scene = default_scene + '_' + states('sensor.day_night').lower() %}

            {% if is_state(period_of_day_scene, 'scening') -%}
              {{ period_of_day_scene }}
            {%- elif is_state(day_night_scene, 'scening') -%}
              {{ day_night_scene }}
            {%- elif is_state(default_scene, 'scening') -%}
              {{ default_scene }}
            {%- else -%}
              off
            {%- endif %}

  # This automation actually sets the scene.
  - alias: living_room_scene_set
    trigger:
      - platform: mqtt
        topic: living_room/scene
    condition:
      - condition: template
        value_template: "{{ is_state(trigger.payload, 'scening') }}"
    action:
      - service: scene.turn_on
        data_template:
          entity_id: "{{ trigger.payload }}"

  # The following automations are just hooks for IHC push buttons.
  - alias: living_room_scene_hygge
    trigger:
      - platform: state
        entity_id: binary_sensor.living_room_scene_hygge
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.living_room_mode
          option: 'Hygge'

  - alias: living_room_scene_spise
    trigger:
    - platform: state
      entity_id: binary_sensor.living_room_scene_spise
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.living_room_mode
          option: 'Spise'

  - alias: living_room_scene_cleaning
    trigger:
    - platform: state
      entity_id: binary_sensor.living_room_scene_cleaning
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.living_room_mode
          option: 'Fra'
      - service: scene.turn_on
        entity_id: scene.rengoring

  - alias: all_off_east
    trigger:
      - platform: state
        entity_id: binary_sensor.all_off_east
        to: 'on'
    action:
      - service: input_select.select_option
        data:
          entity_id: input_select.living_room_mode
          option: 'Fra'
      - service: light.turn_off
        entity_id:
          - light.living_room_dinning_table_pendel
          - light.living_room_couch_table_pendel
          - light.living_room_lamp_at_tv
          - light.living_room_lamp1      
          - light.living_room_glass_cabinet

# Scenes
scene:
- name: living_room_hygge_day
  entities:
    light.living_room_lamp1: off
    light.living_room_spots: off
    light.living_room_dinning_table_pendel:
      state: on
      brightness: 200
      kelvin: 2800
      transition: 5
    light.living_room_couch_table_pendel:
      state: on
      brightness: 200
      kelvin: 2800
      transition: 5
    light.living_room_lamp_at_tv: off
    light.living_room_glass_cabinet: off
      
- name: living_room_hygge_night
  entities:
    light.living_room_lamp1: on
    light.living_room_spots:
      state: on
      brightness_pct: 15
    light.living_room_dinning_table_pendel:
      state: on
      brightness: 128
      kelvin: 2600
      transition: 5
    light.living_room_couch_table_pendel:
      state: on
      brightness: 160
      kelvin: 2500
      transition: 5
    light.living_room_lamp_at_tv:
      state: on
      brightness: 128
      kelvin: 2500
      transition: 5
    light.kitchen_table_lamps: on
    light.living_room_glass_cabinet: on

- name: living_room_spise_day
  entities:
    light.living_room_lamp1: off
    light.living_room_spots: off
    light.living_room_dinning_table_pendel:
      state: on
      brightness: 255
      kelvin: 3000
      transition: 5
    light.living_room_couch_table_pendel: off
    light.living_room_lamp_at_tv: off
    light.living_room_glass_cabinet: off

- name: living_room_spise_night
  entities:
    light.living_room_lamp1: on
    light.living_room_spots:
      state: on
      brightness_pct: 50
    light.living_room_dinning_table_pendel:
      state: on
      brightness: 255
      kelvin: 2800
      transition: 5
    light.living_room_couch_table_pendel:
      state: on
      brightness: 180
      kelvin: 2800
      transition: 5
    light.living_room_lamp_at_tv:
      state: on
      brightness: 180
      kelvin: 2800
      transition: 5
    #light.kitchen_table_lamps: off
    light.living_room_glass_cabinet: on
