homeassistant:
  customize:
    binary_sensor.william_window:
      friendly_name: 'William / Vindue'
    binary_sensor.bedroom_window:
      friendly_name: 'Sovevær. / Vindue'

binary_sensor:
  - platform: mqtt
    name: william_window
    state_topic: 'home-assistant/william/window'
    device_class: window
  - platform: mqtt
    name: bedroom_window
    state_topic: 'home-assistant/bedroom/window'
    device_class: window

# These automations just republish states as retained messages
# when receiving raw input from RF-bridge.
automation:
  - alias: rf_william_window_open
    trigger:
      platform: mqtt
      topic: rfbridge-01/rfin
      payload: '369C01E0053C14B50A'
    action:
      - service: mqtt.publish
        data:
          topic: 'home-assistant/william/window'
          payload: 'ON'
          retain: true
  - alias: rf_william_window_close
    trigger:
      platform: mqtt
      topic: rfbridge-01/rfin
      payload: '366A01D6053C14B50E'
    action:
      - service: mqtt.publish
        data:
          topic: 'home-assistant/william/window'
          payload: 'OFF'
          retain: true
  - alias: rf_bedroom_window_open
    trigger:
      platform: mqtt
      topic: rfbridge-01/rfin
      payload: '369C01CC055014AF0A'
    action:
      - service: mqtt.publish
        data:
          topic: 'home-assistant/bedroom/window'
          payload: 'ON'
          retain: true
  - alias: rf_bedroom_window_close
    trigger:
      platform: mqtt
      topic: rfbridge-01/rfin
      payload: '368801D6054614AF0E'
    action:
      - service: mqtt.publish
        data:
          topic: 'home-assistant/bedroom/window'
          payload: 'OFF'
          retain: true
