homeassistant:
  customize:
    sensor.db_size:
      friendly_name: 'Database Størrelse'
      icon: 'mdi:database'

binary_sensor:
  - platform: ping
    name: ping_ihc_controller
    host: 10.0.1.4
  - platform: ping
    name: ping_hue_bridge
    host: 10.0.1.5

sensor:
  - platform: uptime
  - platform: sql
    db_url: !secret mariadb_url
    scan_interval: 3600
    queries:
      - name: db_size
        query: "select round(sum(data_length + index_length) / 1024 / 1024, 1) as db_size from information_schema.tables WHERE table_schema='homeassistant'"
        column: db_size
        unit_of_measurement: MB
