homeassistant:
  customize:
    sensor.db_size:
      friendly_name: 'Database Størrelse'
      icon: 'mdi:database'

binary_sensor:
  - platform: ping
    name: ping_ihc_controller
    host: 10.0.1.4
  - platform: ping
    name: ping_hue_bridge
    host: 10.0.1.5

sensor:
  # This is also usefull for using the base url in templates.
  - platform: template
    sensors:
      base_url:
        value_template: !secret http_base_url
      ha_token:
        value_template: !secret ha_token
  # Last boot time, Disk, memory & CPU usage
  - platform: systemmonitor
    resources:
      - type: last_boot
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use

mqtt:
  sensor:
    # CPU Temperature - pushed from proxmox usig a cron job
    - name: CPU Temp
      state_topic: system/nuc/temp
      unit_of_measurement: "°C"
      value_template: '{{ value | multiply(0.001) | round(0) }}'

automation:
  - alias: 'system_boot_notification'
    trigger:
    - event: start
      platform: homeassistant
    action:
    - service: notify.telegram_niklas
      data:
        title: "*System Monitoring*"
        message: Home Assistant has started.
