homeassistant:
  customize:
    sensor.db_size:
      friendly_name: 'Database Størrelse'
      icon: 'mdi:database'

binary_sensor:
  - platform: ping
    name: ping_ihc_controller
    host: 10.0.1.4
  - platform: ping
    name: ping_hue_bridge
    host: 10.0.1.5

sensor:
  # Installed hass.io version
  - platform: version
    name: Installed Version
    source: local
  # Latest Available HA Version
  - platform: version
    name: Latest Available Version
    beta: false
    image: raspberrypi3
    source: hassio
  # Last boot time, Disk, memory & CPU usage
  - platform: systemmonitor
    resources:
      - type: last_boot
      - type: disk_use_percent
        arg: /
      - type: memory_use_percent
      - type: processor_use
  - platform: uptime
  # CPU Temperature 
  - platform: command_line
    name: CPU Temp
    command: "cat /sys/class/thermal/thermal_zone0/temp"
    unit_of_measurement: "°C"
    value_template: '{{ value | multiply(0.001) | round(0) }}'
  # Database size
  - platform: sql
    db_url: !secret mariadb_url
    scan_interval: 3600
    queries:
      - name: db_size
        query: "select round(sum(data_length + index_length) / 1024 / 1024, 1) as db_size from information_schema.tables WHERE table_schema='homeassistant'"
        column: db_size
        unit_of_measurement: MB
