# Example configuration.yaml entry for the Telegram Bot
telegram_bot:
  - platform: polling
    api_key: "1034228413:AAGq6Nk0OEHscgaoVia9Tv4-eb_45QPDaHM"
    allowed_chat_ids:
      - 1058128643

notify:
  - name: telegram_niklas
    platform: telegram
    chat_id: 1058128643

automation:
  - alias: telegram_callback_alarm_arm_away
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        command: '/arm_away'
    action:
      - service: alarm_control_panel.alarm_arm_away
        data:
          entity_id: !secret 'alarm_entity_id'
          code: !secret 'alarm_code'
      - service: telegram_bot.edit_replymarkup
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'
          inline_keyboard: []
      - service: telegram_bot.send_message
        data_template:
          target: '{{ trigger.event.data.user_id }}'
          message: 'Alarm tilkoblet!'
  - alias: telegram_callback_dismiss
    trigger:
      platform: event
      event_type: telegram_callback
      event_data:
        command: '/dismiss'
    action:
      - service: telegram_bot.edit_replymarkup
        data_template:
          message_id: '{{ trigger.event.data.message.message_id }}'
          chat_id: '{{ trigger.event.data.chat_id }}'
          inline_keyboard: []
      - service: telegram_bot.answer_callback_query
        data_template:
          callback_query_id: '{{ trigger.event.data.id }}'
          message: 'Modtaget! Jeg gør ikke mere...'
