homeassistant:
  customize:
    automation.welcome_home_at_night:
      friendly_name: 'Velkomst aften'
    binary_sensor.driveway_doors:
      friendly_name: 'Døre mod indkørsel (Bryggers og Hoveddør)'  

input_boolean:
  welcome_home_at_night_active:
    name: 'Velkomst aften aktiv'
    initial: off

binary_sensor:
  - name: driveway_doors
    platform: group
    entities:
      - binary_sensor.front_door_contact
      - binary_sensor.utility_room_door_contact

# Automations
automation:
- alias: welcome_home_at_night
  trigger:
  - platform: zone
    entity_id: device_tracker.niklas_mobile
    zone: zone.near_home
    event: enter
  - platform: zone
    entity_id: device_tracker.karinas_iphone_12
    zone: zone.near_home
    event: enter
  condition:
  - condition: state
    entity_id: group.family
    state: not_home
  - condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  - condition: state
    entity_id: light.outdoor_driveway_spots
    state: 'off'
  - condition: state
    entity_id: input_boolean.welcome_home_at_night_active
    state: 'off'
  action:
  - service: input_boolean.turn_on
    data:
      entity_id: input_boolean.welcome_home_at_night_active
  - service: light.turn_on
    entity_id: light.outdoor_driveway_spots
  - service: light.turn_on
    entity_id: light.living_room_spots
    data_template:
      brightness: 64
  - wait_for_trigger:
    - platform: state
      entity_id: binary_sensor.utility_room_door_contact
      to: 'on'
    - platform: state
      entity_id: binary_sensor.front_door_contact
      to: 'on'
  - delay: '00:10:00'
  - service: light.turn_off
    entity_id: light.outdoor_driveway_spots
  - service: input_boolean.turn_off
    data:
      entity_id: input_boolean.welcome_home_at_night_active
