homeassistant:
  customize:
    sensor.bedroom_temperature:
      friendly_name: Sovevær. / Temp.
    sensor.bedroom_humidity:
      friendly_name: Sovevær. / Luftfugt.
      
sensor:
- platform: mqtt
  name: bedroom_temperature
  state_topic: bedroom/sensor/temperature/state
  availability_topic: bedroom/status
  unit_of_measurement: °C
- platform: mqtt
  name: bedroom_humidity
  state_topic: bedroom/sensor/humidity/state
  availability_topic: bedroom/status
  unit_of_measurement: '%'
