# TODO: This could all be done more elegantly with auto discovery, but if this is to be enabled then I need to disable or modify the
# auto-discovery of the floor heating system first.
sensor:
  # Temperature 1: Gæste badeværelse
  - platform: mqtt
    name: guest_bathroom_temperature
    unit_of_measurement: "°C"
    device_class: temperature
    value_template: "{{ value_json.temperature }}"
    state_topic: zigbee2mqtt/guest_bathroom_temperature
    #json_attributes_topic: zigbee2mqtt/guest_bathroom_temperature
    availability_topic: zigbee2mqtt/bridge/state
    unique_id: 0x00158d0002b882dd_temperature_zigbee2mqtt
  - platform: mqtt
    name: guest_bathroom_humidity
    unit_of_measurement: "%"
    device_class: humidity
    value_template: "{{ value_json.humidity }}"
    state_topic: zigbee2mqtt/guest_bathroom_temperature
    #json_attributes_topic: zigbee2mqtt/guest_bathroom_temperature
    availability_topic: zigbee2mqtt/bridge/state
    unique_id: 0x00158d0002b882dd_humidity_zigbee2mqtt
  - platform: mqtt
    name: guest_bathroom_pressure
    unit_of_measurement: hPa
    device_class: pressure
    value_template: "{{ value_json.pressure }}"
    state_topic: zigbee2mqtt/guest_bathroom_temperature
    #json_attributes_topic: zigbee2mqtt/guest_bathroom_temperature
    availability_topic: zigbee2mqtt/bridge/state    
    unique_id: 0x00158d0002b882dd_pressure_zigbee2mqtt
  # PIR 1 - Bryggers
  - platform: mqtt
    name: utility_room_illuminance
    unit_of_measurement: lx
    device_class: illuminance
    value_template: "{{ value_json.illuminance }}"
    state_topic: zigbee2mqtt/utility_room_occupancy
    #json_attributes_topic: zigbee2mqtt/utility_room_occupancy
    availability_topic: zigbee2mqtt/bridge/state
    unique_id: 0x00158d0002b8fc1b_illuminance_zigbee2mqtt

binary_sensor:
  # PIR 1 - Bryggers
  - platform: mqtt
    name: utility_room_occupancy
    payload_on: true
    payload_off: false
    value_template: "{{ value_json.occupancy }}"
    device_class: motion
    state_topic: zigbee2mqtt/utility_room_occupancy
    #json_attributes_topic: zigbee2mqtt/utility_room_occupancy
    availability_topic: zigbee2mqtt/bridge/state
    unique_id: 0x00158d0002b8fc1b_occupancy_zigbee2mqtt
  - platform: mqtt
    name: living_room_window
    payload_on: false
    payload_off: true
    value_template: "{{ value_json.contact }}"
    device_class: window
    state_topic: zigbee2mqtt/living_room_window
    #json_attributes_topic: zigbee2mqtt/living_room_window
    availability_topic: zigbee2mqtt/bridge/state
    unique_id: 0x00158d0002bfe535_contact_zigbee2mqtt
